// <auto-generated />
using caja.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace caja.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180228170322_AddedTillAndTallyModels")]
    partial class AddedTillAndTallyModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("caja.Models.Tally", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<decimal>("Final");

                    b.Property<int?>("TillId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TillId");

                    b.HasIndex("UserId");

                    b.ToTable("Tallies");
                });

            modelBuilder.Entity("caja.Models.Till", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Number");

                    b.Property<string>("Store");

                    b.HasKey("Id");

                    b.ToTable("Tills");
                });

            modelBuilder.Entity("caja.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("caja.Models.Tally", b =>
                {
                    b.HasOne("caja.Models.Till")
                        .WithMany("Tallies")
                        .HasForeignKey("TillId");

                    b.HasOne("caja.Models.User")
                        .WithMany("Tallies")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
